from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
from io import BytesIO

def create_docx(project_title: str, sections: list):
    doc = Document()
    doc.add_heading(project_title, 0)
    
    for section in sections:
        doc.add_heading(section.title, level=1)
        if section.content:
            doc.add_paragraph(section.content)
        else:
            doc.add_paragraph("[No content generated]")
            
    # Save to buffer
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def create_pptx(project_title: str, sections: list):
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = project_title
    subtitle.text = "Generated by AI Doc Platform"
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for section in sections:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = section.title
        
        tf = body_shape.text_frame
        if section.content:
            tf.text = section.content
        else:
            tf.text = "[No content generated]"
            
    # Save to buffer
    buffer = BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer
